import "./globals.css"
import Layout from "./components/layout";
import styled from "styled-components"
import StyledComponentsRegistry from '../lib/styledComponentsRegistry';

export const metadata = {
  title: 'The Niceness Challenge',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
  return (
   <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Layout>
            {children}
          </Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
