export const metadata = {
  title: 'The Niceness Challenge',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  )
}
